collections:
  diensten:
    output: true
    permalink: /:collection/:name/
  methodes:
    output: true
    permalink: /:collection/:name/
  projecten:
    output: true
    permalink: /:collection/:name/
  klanten:
    output: true
    permalink: /:collection/:name/
  testimonials:
    output: true
    permalink: /:collection/:name/
  peeps:
    output: true
    permalink: /:collection/:name/
  waarden:
    output: true
    permalink: /:collection/:name/
  materialen:
    output: true
    permalink: /:collection/:name/